# Generated by Django 4.1.2 on 2023-02-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='days',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='professor',
            name='middle_initial',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_description',
            field=models.CharField(max_length=200),
        ),
    ]
